### ISSUE TITLE
The editor does not fill the contents from the database

### ISSUE THREAD

**Issue by ifdancoder** [athphane/filament-editorjs#1]
### What happened?

The contents are saved correctly in the database, but the editor does not fill the contents from the database

### How to reproduce the bug

I really do not know. The contents from the database have never filled the editor.

### Package Version

Latest

### PHP Version

8.3

### Laravel Version

11

**Comment by athphane** [comment]
Sorry for the late response @ifdancoder. The issue JUST NOW caught my attention. 

If you could provide an error reproducing repository I would love to help you.

If you managed the figure out what the issue was then let me know as well.

**Comment by prosvitco** [comment]
Had a similar issue with a custom field - you need to cast it manually to json in the model
